using SQLParity.Core.Comparison;
using Xunit;

namespace SQLParity.Core.Tests.Comparison;

public class AutoGeneratedConstraintNameTests
{
    [Theory]
    [InlineData("PK__AlcoholD__3214EC272833E366")]
    [InlineData("DF__Orders__Status__1A14E395")]
    [InlineData("CK__Orders__Amount__1AB6E48F")]
    [InlineData("UQ__Orders__1B0907CE")]
    [InlineData("FK__Orders__CustId__1C5806F2")]
    public void IsAutoGenerated_RecognizesSmoGeneratedNames(string name)
    {
        Assert.True(AutoGeneratedConstraintName.IsAutoGenerated(name));
    }

    [Fact]
    public void IsAutoGenerated_TreatsEmptyOrNullAsAuto()
    {
        Assert.True(AutoGeneratedConstraintName.IsAutoGenerated(""));
        Assert.True(AutoGeneratedConstraintName.IsAutoGenerated(null!));
    }

    [Theory]
    [InlineData("PK_Orders_Id")]
    [InlineData("DF_Orders_Status")]
    [InlineData("CK_Positive_Amount")]
    [InlineData("FK_OrderItems_Order")]
    public void IsAutoGenerated_RejectsHandNamedConstraints(string name)
    {
        Assert.False(AutoGeneratedConstraintName.IsAutoGenerated(name));
    }

    [Theory]
    [InlineData("PK__AlcoholD__3214EC272833E366", "")]
    [InlineData("", "")]
    [InlineData("PK_Orders_Id", "PK_Orders_Id")]
    [InlineData("FK_OrderItems_Order", "FK_OrderItems_Order")]
    public void Canonicalize_StripsAutoGenLeavesUserNamed(string input, string expected)
    {
        Assert.Equal(expected, AutoGeneratedConstraintName.Canonicalize(input));
    }
}
