using System.Text.RegularExpressions;

namespace SQLParity.Core.Comparison;

/// <summary>
/// SQL Server / SMO auto-generates constraint names of these shapes
/// (case-insensitive):
///   DEFAULT:     DF__&lt;table-prefix&gt;__&lt;col-prefix&gt;_&lt;hex&gt;
///   PRIMARY KEY: PK__&lt;table-prefix&gt;__&lt;hex&gt;
///   CHECK:       CK__&lt;table-prefix&gt;__&lt;col-prefix&gt;_&lt;hex&gt;
///   UNIQUE:      UQ__&lt;table-prefix&gt;__&lt;hex&gt;
///   FOREIGN KEY: FK__&lt;table-prefix&gt;__&lt;reftable-prefix&gt;__&lt;hex&gt;
/// These names carry no user intent and differ across environments, so we
/// treat them as equivalent to anonymous (empty-name) constraints both when
/// rendering canonical CREATE TABLE output and when matching constraints
/// across two sides of a comparison.
/// </summary>
public static class AutoGeneratedConstraintName
{
    private static readonly Regex Pattern = new(
        @"^(?:" +
        @"DF__[A-Za-z0-9_]+__[A-Za-z0-9_]+_[A-Fa-f0-9]{6,}" +
        @"|CK__[A-Za-z0-9_]+__[A-Za-z0-9_]+_[A-Fa-f0-9]{6,}" +
        @"|PK__[A-Za-z0-9_]+__[A-Fa-f0-9]{6,}" +
        @"|UQ__[A-Za-z0-9_]+__[A-Fa-f0-9]{6,}" +
        @"|FK__[A-Za-z0-9_]+__[A-Za-z0-9_]+__[A-Fa-f0-9]{6,}" +
        @")$",
        RegexOptions.Compiled);

    public static bool IsAutoGenerated(string? name)
    {
        if (string.IsNullOrEmpty(name)) return true;
        return Pattern.IsMatch(name);
    }

    /// <summary>
    /// Returns an empty string for auto-generated or empty names; otherwise
    /// returns the name unchanged. Use this as a dictionary key when matching
    /// constraints across two schema sides.
    /// </summary>
    public static string Canonicalize(string? name) =>
        IsAutoGenerated(name) ? string.Empty : name!;
}
