using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using SQLParity.Core.Model;
using SQLParity.Core.Parsing;
using Xunit;

namespace SQLParity.Core.Tests.Parsing;

public class FolderSyncWriterTests
{
    private sealed class TempFolder : IDisposable
    {
        public string Path { get; }
        public TempFolder()
        {
            Path = System.IO.Path.Combine(System.IO.Path.GetTempPath(),
                "SQLParity_WRITER_" + Guid.NewGuid().ToString("N"));
            Directory.CreateDirectory(Path);
        }
        public string WriteFile(string name, string contents)
        {
            var full = System.IO.Path.Combine(Path, name);
            File.WriteAllText(full, contents);
            return full;
        }
        public string Read(string name)
            => File.ReadAllText(System.IO.Path.Combine(Path, name));
        public void Dispose()
        {
            try { Directory.Delete(Path, recursive: true); } catch { /* best effort */ }
        }
    }

    private static FolderSchemaContext ContextFor(string folderPath, params (SchemaQualifiedName Id, string Path, bool Single)[] entries)
    {
        var dict = entries.ToDictionary(
            e => e.Id,
            e => new FileBacking { FilePath = e.Path, IsSingleObjectFile = e.Single });
        return new FolderSchemaContext
        {
            ObjectToFile = dict,
            ParseWarnings = Array.Empty<string>(),
            FolderPath = folderPath,
        };
    }

    private static Change ChangeFor(
        ObjectType type, string schema, string name, ChangeStatus status,
        string? ddlA = null, string? ddlB = null) => new()
    {
        Id = SchemaQualifiedName.TopLevel(schema, name),
        ObjectType = type,
        Status = status,
        DdlSideA = ddlA,
        DdlSideB = ddlB,
        ColumnChanges = Array.Empty<ColumnChange>(),
    };

    private static readonly DateTime FixedNow = new(2026, 4, 29, 14, 30, 0, DateTimeKind.Utc);

    [Fact]
    public void NewObject_CreatesFileWithConventionName()
    {
        using var t = new TempFolder();
        var change = ChangeFor(ObjectType.StoredProcedure, "dbo", "GetOrders",
            ChangeStatus.New,
            ddlA: "CREATE PROCEDURE [dbo].[GetOrders] AS SELECT 1");

        var manifest = new FolderSyncWriter().WriteChanges(
            new[] { change }, ContextFor(t.Path),
            "srv", "MyDb", FixedNow);

        var created = Assert.Single(manifest.FilesCreated);
        Assert.Equal("PROC.dbo.GetOrders.sql", Path.GetFileName(created));
        Assert.Empty(manifest.Errors);

        string content = File.ReadAllText(created);
        Assert.Contains("USE [MyDb];", content);
        Assert.Contains("CREATE OR ALTER PROCEDURE", content);
    }

    [Fact]
    public void GeneratedHeader_IsFollowedByGoBeforeCreate()
    {
        using var t = new TempFolder();
        var change = ChangeFor(ObjectType.StoredProcedure, "dbo", "Foo",
            ChangeStatus.New, ddlA: "CREATE PROCEDURE [dbo].[Foo] AS SELECT 1");

        new FolderSyncWriter().WriteChanges(new[] { change }, ContextFor(t.Path),
            "srv", "MyDb", FixedNow);

        string content = t.Read("PROC.dbo.Foo.sql");
        // The sequence: USE → GO → blank → SQLParity header lines → GO → blank → CREATE.
        // The GO immediately preceding CREATE is what isolates our header from the
        // proc body in sys.sql_modules.definition.
        var lines = content.Split(new[] { "\r\n", "\n" }, StringSplitOptions.None);
        int useLine = Array.FindIndex(lines, l => l.StartsWith("USE [MyDb]", StringComparison.Ordinal));
        int generatedLine = Array.FindIndex(lines, l => l.StartsWith("-- Generated by SQLParity", StringComparison.Ordinal));
        // Match the actual CREATE statement, not the comment line that mentions
        // "CREATE OR ALTER guard" — exclude lines starting with "--".
        int createLine = Array.FindIndex(lines, l =>
            l.TrimStart().StartsWith("CREATE OR ALTER", StringComparison.OrdinalIgnoreCase));
        Assert.True(useLine >= 0 && useLine < generatedLine, "USE must precede generated header.");
        Assert.True(generatedLine < createLine, "Generated header must precede CREATE.");

        // A line between the generated header and CREATE must be exactly "GO"
        // (possibly with surrounding whitespace).
        bool hasGoBetween = false;
        for (int i = generatedLine + 1; i < createLine; i++)
        {
            if (lines[i].Trim().Equals("GO", StringComparison.OrdinalIgnoreCase))
            {
                hasGoBetween = true;
                break;
            }
        }
        Assert.True(hasGoBetween, "Expected a GO line between the SQLParity header and CREATE.");
    }

    [Fact]
    public void ModifiedObjectInSingleFile_OverwritesInPlace()
    {
        using var t = new TempFolder();
        var existing = t.WriteFile("PROC.dbo.A.sql", "-- old content");
        var change = ChangeFor(ObjectType.StoredProcedure, "dbo", "A", ChangeStatus.Modified,
            ddlA: "CREATE PROCEDURE [dbo].[A] AS SELECT 999",
            ddlB: "-- old content");

        var ctx = ContextFor(t.Path, (change.Id, existing, Single: true));
        var manifest = new FolderSyncWriter().WriteChanges(new[] { change }, ctx,
            "srv", "MyDb", FixedNow);

        var updated = Assert.Single(manifest.FilesUpdated);
        Assert.Equal(existing, updated);
        Assert.Empty(manifest.FilesCreated);

        string content = File.ReadAllText(existing);
        Assert.Contains("SELECT 999", content);
        Assert.DoesNotContain("-- old content", content);
    }

    [Fact]
    public void ModifiedObjectInMultiFile_SplitsIntoIndividualFilesAndCommentsOriginal()
    {
        using var t = new TempFolder();
        const string original =
            "CREATE PROCEDURE dbo.Helper1 AS SELECT 1\n" +
            "GO\n" +
            "CREATE PROCEDURE dbo.Helper2 AS SELECT 2\n" +
            "GO\n";
        var multiFile = t.WriteFile("helpers.sql", original);

        var helper1Id = SchemaQualifiedName.TopLevel("dbo", "Helper1");
        var helper2Id = SchemaQualifiedName.TopLevel("dbo", "Helper2");
        var ctx = ContextFor(t.Path,
            (helper1Id, multiFile, Single: false),
            (helper2Id, multiFile, Single: false));

        // Only Helper1 changed in the DB. Helper2 should still get its own
        // file (per spec: force every object into its own file once we touch
        // a multi-object file).
        var change = new Change
        {
            Id = helper1Id,
            ObjectType = ObjectType.StoredProcedure,
            Status = ChangeStatus.Modified,
            DdlSideA = "CREATE PROCEDURE dbo.Helper1 AS SELECT 999",
            DdlSideB = "CREATE PROCEDURE dbo.Helper1 AS SELECT 1",
            ColumnChanges = Array.Empty<ColumnChange>(),
        };

        var manifest = new FolderSyncWriter().WriteChanges(new[] { change }, ctx,
            "srv", "MyDb", FixedNow);

        // Two new files (one per object originally in the multi-file).
        Assert.Equal(2, manifest.FilesCreated.Count);
        Assert.Contains(manifest.FilesCreated, p => Path.GetFileName(p) == "PROC.dbo.Helper1.sql");
        Assert.Contains(manifest.FilesCreated, p => Path.GetFileName(p) == "PROC.dbo.Helper2.sql");

        // Original helpers.sql is now commented out.
        Assert.Equal(multiFile, Assert.Single(manifest.FilesCommentedOut));
        string commentedContent = File.ReadAllText(multiFile);
        Assert.Contains("-- Split into per-object files", commentedContent);
        Assert.Contains("/*", commentedContent);
        Assert.Contains("CREATE PROCEDURE dbo.Helper1 AS SELECT 1", commentedContent); // original preserved
        Assert.Contains("*/", commentedContent);

        // Helper1's file uses the new DDL, Helper2's uses the parsed (unchanged) DDL.
        string h1 = File.ReadAllText(manifest.FilesCreated.Single(p => p.EndsWith("Helper1.sql")));
        Assert.Contains("SELECT 999", h1);
        string h2 = File.ReadAllText(manifest.FilesCreated.Single(p => p.EndsWith("Helper2.sql")));
        Assert.Contains("SELECT 2", h2);
    }

    [Fact]
    public void DroppedObjectInSingleFile_RewritesAsDropFileWithCommentedOriginal()
    {
        using var t = new TempFolder();
        const string original = "CREATE PROCEDURE [dbo].[OldProc] AS SELECT 1";
        var path = t.WriteFile("PROC.dbo.OldProc.sql", original);

        var change = ChangeFor(ObjectType.StoredProcedure, "dbo", "OldProc",
            ChangeStatus.Dropped,
            ddlB: original);

        var ctx = ContextFor(t.Path, (change.Id, path, Single: true));
        var manifest = new FolderSyncWriter().WriteChanges(new[] { change }, ctx,
            "srv", "MyDb", FixedNow);

        Assert.Equal(path, Assert.Single(manifest.FilesUpdated));
        string content = File.ReadAllText(path);
        Assert.Contains("DROP PROCEDURE IF EXISTS [dbo].[OldProc]", content);
        Assert.Contains("REMOVED from source database", content);
        Assert.Contains("/*", content);
        Assert.Contains("CREATE PROCEDURE [dbo].[OldProc]", content); // original preserved in comment
        Assert.Contains("*/", content);
    }

    [Fact]
    public void NewObjectFilenameCollision_AppendsNumericSuffix()
    {
        using var t = new TempFolder();
        // A file with the desired name already exists (and isn't backing this object).
        t.WriteFile("PROC.dbo.GetOrders.sql", "-- some unrelated file");

        var change = ChangeFor(ObjectType.StoredProcedure, "dbo", "GetOrders",
            ChangeStatus.New,
            ddlA: "CREATE PROCEDURE [dbo].[GetOrders] AS SELECT 1");

        var manifest = new FolderSyncWriter().WriteChanges(new[] { change }, ContextFor(t.Path),
            "srv", "MyDb", FixedNow);

        var created = Assert.Single(manifest.FilesCreated);
        Assert.Equal("PROC.dbo.GetOrders_1.sql", Path.GetFileName(created));
        // The original file untouched.
        Assert.Equal("-- some unrelated file", t.Read("PROC.dbo.GetOrders.sql"));
    }

    [Fact]
    public void NewSchema_GetsExpectedFilename()
    {
        using var t = new TempFolder();
        var change = new Change
        {
            Id = SchemaQualifiedName.TopLevel("audit", "audit"),
            ObjectType = ObjectType.Schema,
            Status = ChangeStatus.New,
            DdlSideA = "CREATE SCHEMA [audit]",
            DdlSideB = null,
            ColumnChanges = Array.Empty<ColumnChange>(),
        };

        var manifest = new FolderSyncWriter().WriteChanges(new[] { change }, ContextFor(t.Path),
            "srv", "MyDb", FixedNow);

        var created = Assert.Single(manifest.FilesCreated);
        Assert.Equal("SCHEMA.audit.sql", Path.GetFileName(created));
    }

    [Fact]
    public void NewTable_WrappedWithObjectIdGuardNotDrop()
    {
        using var t = new TempFolder();
        var change = ChangeFor(ObjectType.Table, "dbo", "Orders", ChangeStatus.New,
            ddlA: "CREATE TABLE [dbo].[Orders] (Id INT NOT NULL)");

        new FolderSyncWriter().WriteChanges(new[] { change }, ContextFor(t.Path),
            "srv", "MyDb", FixedNow);

        string content = t.Read("TABLE.dbo.Orders.sql");
        Assert.Contains("IF OBJECT_ID(N'[dbo].[Orders]', N'U') IS NULL", content);
        Assert.DoesNotContain("DROP TABLE", content);
    }

    [Fact]
    public void Manifest_RecordsCorrectCategoriesPerChange()
    {
        using var t = new TempFolder();
        var existing = t.WriteFile("PROC.dbo.Mod.sql", "-- old");
        var multi = t.WriteFile("multi.sql", "CREATE PROC dbo.M1 AS SELECT 1\nGO\n");

        var modId = SchemaQualifiedName.TopLevel("dbo", "Mod");
        var m1Id = SchemaQualifiedName.TopLevel("dbo", "M1");
        var ctx = ContextFor(t.Path,
            (modId, existing, Single: true),
            (m1Id, multi, Single: false));

        var changes = new[]
        {
            new Change
            {
                Id = modId, ObjectType = ObjectType.StoredProcedure,
                Status = ChangeStatus.Modified,
                DdlSideA = "CREATE PROC dbo.Mod AS SELECT 999",
                DdlSideB = "-- old",
                ColumnChanges = Array.Empty<ColumnChange>(),
            },
            new Change
            {
                Id = m1Id, ObjectType = ObjectType.StoredProcedure,
                Status = ChangeStatus.Modified,
                DdlSideA = "CREATE PROC dbo.M1 AS SELECT 999",
                DdlSideB = "CREATE PROC dbo.M1 AS SELECT 1",
                ColumnChanges = Array.Empty<ColumnChange>(),
            },
            new Change
            {
                Id = SchemaQualifiedName.TopLevel("dbo", "BrandNew"),
                ObjectType = ObjectType.StoredProcedure,
                Status = ChangeStatus.New,
                DdlSideA = "CREATE PROC dbo.BrandNew AS SELECT 1",
                DdlSideB = null,
                ColumnChanges = Array.Empty<ColumnChange>(),
            },
        };

        var manifest = new FolderSyncWriter().WriteChanges(changes, ctx, "srv", "MyDb", FixedNow);

        Assert.Single(manifest.FilesUpdated);     // PROC.dbo.Mod.sql overwritten in place
        Assert.Single(manifest.FilesCommentedOut); // multi.sql commented out
        // Created: M1 (extracted from multi-file) + BrandNew = 2.
        Assert.Equal(2, manifest.FilesCreated.Count);
        Assert.Empty(manifest.Errors);
    }

    [Fact]
    public void ModifiedChange_WithoutSourceFileMapping_IsSkipped()
    {
        using var t = new TempFolder();
        // No mapping in context — change should be skipped, not crash.
        var change = ChangeFor(ObjectType.StoredProcedure, "dbo", "Ghost",
            ChangeStatus.Modified, ddlA: "CREATE PROC dbo.Ghost AS SELECT 1");

        var manifest = new FolderSyncWriter().WriteChanges(
            new[] { change }, ContextFor(t.Path), "srv", "MyDb", FixedNow);

        var skip = Assert.Single(manifest.Skipped);
        Assert.Contains("Ghost", skip);
        Assert.Empty(manifest.Errors);
        Assert.Empty(manifest.FilesUpdated);
    }
}
